### ISSUE TITLE
PCSend & CtrlSend

### ISSUE THREAD

**Issue by gleb812** [gleb812/pch2csd#10]
Modules PCSend & CtrlSend. I tested them on external MIDI sequencer via soundcard's MIDI port. They work. But regarding MID Channel settings of these modules, Nord also had This and SlotA, SlotB, SlotC, SlotD. 
'This' is a shortcut to current MIDI channel of selected slot. Others are self-explaining. So far we are far away from Slot concepts. So maybe we may leave it as is.

Another thing is time interval between input impulse and output impulse. My card shows it varies (from dozens of samples @ 96K to several hundreds). Demo (even hacked one) doesn't support these modules.
If we prove that this variable interval is a Clavia special, then we can just insert some random delay...

**Comment by ech2** [comment]
@gleb812 I forgot to mention that I checked the hacked demo only on Linux. Which means it may have bugs with MIDI support in *wine*. You can try to run the test patch (bellow) in hacked demo on Windows and listen if you hear the delay in headphones?

![2018-03-08-192536_516x137_scrot](https://user-images.githubusercontent.com/1007225/37166087-ceed6dd6-2306-11e8-8243-b3c15342a947.png)

**Comment by gleb812** [comment]
@ech2 Nope, I tried running Demo on XP. It behaves the same way - locked modules are not working.
So the click-click effect will be heard only in normal software.
