### ISSUE TITLE
A Funny Thing with CLKGEN

### ISSUE THREAD

**Issue by gleb812** [gleb812/pch2csd#12]
Actually, NM's clock generator doesn't generate 1-sample length pulses. Moreover, it isn't some kind of fixed length pulses. Nord clock generator behaves almost like an ordinary oscillator. I just checked different BPM with different clock dividers (Sync every 1, 2, 4, etc beats) and I can say that

a) A Sync osc is approximately 1:400 pulse 
b) 1/16 osc is approximately 1:18 pulse
c) 1/96 osc is approximately 1:12 pulse

ClockActive is always 1 if Clk is ON. 

So I need to fix my code to make it closer to the original. BTW, you can even try Amplitude Modulation using ClkGen...

**Comment by gleb812** [comment]
So I revisited the ClkGen code. Now it is rather tiny. Swing parameter (the problem of the previous version) should work well now. It is done through table warping. Also notice that simple table opcodes are used. Even the lowest wave seems OK in the sense of its fronts..

**Comment by gleb812** [comment]
Also added three more ftables to the common file... @ech2 maybe we should start making includes? I estimate couple more tables...

**Comment by ech2** [comment]
Hey @gleb812,

If I’m not mistaken the tool already includes multiple function table files that have file names `csd_ft_*.txt` (https://github.com/gleb812/pch2csd/blob/master/pch2csd/csdgen.py#L342).

**Comment by ech2** [comment]
I did you mean something else?
