### ISSUE TITLE
Missing mapping table for the LevAmp dB amplitude scale 

### ISSUE THREAD

**Issue by ech2** [gleb812/pch2csd#14]
I don’t see a proper dB scale table to use with the LevAmp module. @gleb812 could you check it up, please? Maybe I’m looking in a wrong place or something…

**Comment by gleb812** [comment]
@ech2 gonna check asap. Physically in Moscow now. Have to find clavia_maps xls file. Maybe in mailbox...

**Comment by gleb812** [comment]
@ech2 me cannot find it in a mailbox. Should be on my home PC. Also maybe Misha still has it. I remember these was a table for dB. But maybe it was for some different part...

**Comment by ech2** [comment]
@gleb812 thisfile is in the repository:
https://github.com/gleb812/pch2csd/blob/35f26749f27159f61c52e7c5b28ff1b4d18bf750/docs/value_maps.ods

**Comment by gleb812** [comment]
@ech2 added LVLadb table.
