### ISSUE TITLE
error: error (163.txt): the UDO 'OscShpA' is invalid

### ISSUE THREAD

**Issue by MacroMachines** [gleb812/pch2csd#23]
EDIT: Nevermind, I looked back at the start of the doc and found what I needed, module creation and list of modules that aren't implemented, and I luckily got the regular editor going on my laptop, but it doesn't make any sound, so I might have to borrow a friends nord modular to edit.

----

I tried my first patch conversion and I got this error:

> NICHOLASs-MacBook-Pro:~ nicholascraftisiii$ pch2csd /Users/nicholascraftisiii/Dropbox/_OMI_NICO/NORDG2-CSOUND-CABBAGE/G2P
> atches/magicbox2.pch2 
> error: error (163.txt): the UDO 'OscShpA' is invalid
> please, run 'pch2csd -c 163' for details
> NICHOLASs-MacBook-Pro:~ nicholascraftisiii$ pch2csd -c 163
> checking module type '163' (163.txt)
> module name: OscShpA
> error: no template file for the module with id 163
> NICHOLASs-MacBook-Pro:~ nicholascraftisiii$ 
> 

How can I potentially help in resolving some of these modules that don't exist to work?  

I would really love it if I could convert the really awesome nord modular patches I have made in the past into cabbage to turn them into VSTs I can use in the future.  This would also be a really cool workflow for programming virtual instruments depending on what is supported.  I'd just love to test convert one of my cool patches to see if it is a viable thing, but I am fairly sure that nearly all of my patches make use of one or a few unsupported modules.  

is there either A) a way I can help figure out how to convert the unsupported ones or for now B) replace the modules that don't work with something nearby that might work as a replacement without needing to use the Nord hardware / software?  as I sold my nord a while back and am fairly sure that my laptop no longer runs the demo editor.

**Comment by MacroMachines** [comment]
Im looking through the list now, is everthing that says no template mean its not implimented?  Some of those are my most used modules :/

**Comment by MacroMachines** [comment]
I tried modifying my patch to not use the module that gave the error, and now I am getting:

> NICHOLASs-MacBook-Pro:~ nicholascraftisiii$ pch2csd /Users/nicholascraftisiii/Dropbox/_OMI_NICO/NORDG2-CSOUND-CABBAGE/G2P
> atches/magicbox2b.pch2 
> list index out of range
> NICHOLASs-MacBook-Pro:~ nicholascraftisiii$ 
>

**Comment by gleb812** [comment]
Thanks for your interest to the project! please mail me gleb.rogozinsky@gmail.com 
I would suggest small video tut
