### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by ShoveD01** [gleb812/pch2csd#24]

**Comment by gleb812** [comment]
Hi, StoveD01! Yes, it is active, though due to my upcoming thesid defence preparations I am a bit out. Will definetely back to it later. If any questions, please ask

**Comment by ShoveD01** [comment]
Would I be right in saying although the csound code is generated
Controls and I/O have to be added later?
I am able to get code into cabbage for example, but I am having to work out where to add controls.

**Comment by gleb812** [comment]
Yes, all the pch2csd does is turning the NM2 patch into Csound code. We were always focused on full implementation of any unit of NM2. After that, we see two ways - one is Cabbage-based fork, another is collab with some open NM2 editor

**Comment by alfonso73** [comment]
hi! any new version coming with more modules implemented? thanks!

**Comment by gleb812** [comment]
hi! sure. I just need time to survive my defense in the end of June. After that I guess we'll be back on track with new modules and everything

**Comment by gleb812** [comment]
so finally we continue - I've upload complete SEQ group today

**Comment by alfonso73** [comment]
@gleb812 That's great! Hope to see all the modules implemented and test some Cabbage port of the generated .orc
