### ISSUE TITLE
parser does not detect MODE kWave in LfoC

### ISSUE THREAD

**Issue by zappfinger** [gleb812/pch2csd#7]
The wave selection in LfoC is not a _parameter_, but a _mode_ (according to ModelDef.xml). It is not picked up by the parser

**Comment by gleb812** [comment]
Got it! In process.

**Comment by ech2** [comment]
OK, I did this. Example of the generated code is bellow. Also added a notion to the tutorial: https://github.com/gleb812/pch2csd/wiki/Making-a-new-module

```
; --------------------
; VOICE AREA
instr 1
; Module    Parameters     Modes    Inlets      Outlets
LfoC        62.9,0,4,1,1,  0,       1,                0
LfoC        59.4,0,4,1,1,  1,       1,                0
LfoC        56.0,0,4,1,1,  2,       1,                0
LfoC        52.9,0,4,1,1,  3,       1,                0
LfoC        49.9,0,4,1,1,  4,       1,                0
LfoC        47.1,0,4,1,1,  5,       1,                0
LfoC        44.5,0,4,1,1,  6,       1,                0
LfoC        42.0,0,4,1,1,  7,       1,                0
endin
```

**Comment by ech2** [comment]
https://github.com/gleb812/pch2csd/commit/17da58f76c73ec9bc84676c4b3881e5718a3a7be

**Comment by zappfinger** [comment]
I am not sure how to use this. I extended the template for LfoC with an 
extra 'parameter' and now I get:

RMA:NMpatches richard$ pch2csd lfoC2OscA.pch2
warning: template 'UdoTemplate(LfoC, 24.txt)' has different number of 
parameters than it was found in the parsed module 'Module(type=24, 
modes=[1], location=Location.VOICE_AREA, type_name=LfoC, id=1)'. 
Returning -1s for now.
RMA:NMpatches richard$ pch2csd -p lfoC2OscA.pch2
Patch file: lfoC2OscA.pch2

Modules
Name      ID    Type  Parameters               Modes    Area
------  ----  ------  -----------------------  -------  ------
LfoC       1      24  [57, 0, 5, 1, 1]         [1]      VOICE
OscA       2      97  [62, 64, 1, 0, 2, 0, 1]  []       VOICE
Out2       3       4  [0, 1, 0]                []       VOICE


How do I get the 'mode' value?

**Comment by ech2** [comment]
@zappfinger Did you include “modes” as arguments to the `;@ args` annotation? I made modes special and they don’t need to be included there. You only need to modify the `opcode` definition to accomodate modes --- they will be included as typical arguments.

E.g. if you have your annotation like this: `;@ args kkk,k,k` and you have two mode variables, then your opcode annotation should be like this: `opcode SomeName, 0, iiiiiii` (seven i’s).

**Comment by ech2** [comment]
The motivation for this was to not have to include `;@ map` annotation for modes. Do you think this solution is counter-intuitive?

**Comment by zappfinger** [comment]
Ok, i got it now, thanks!
